### ISSUE TITLE
Have experience with GitHub & Git

### ISSUE THREAD

**Issue by cOsprey** [cOsprey/GSoC-pgRouting#1]
- [x] Fork the [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting) repository
- [x] activate issues in your fork
- [x] open an issue in your fork and put this content on the issue
- [x] Clone your fork repository in your computer
- [x] Create remote named `upstream` pointing to https://github.com/pgRouting/pgrouting
- [x] checkout to the master branch of `upstream`
- [x] create new branch with name `gsoc-test`
- [x] push the newly created branch
- [x] put link of branch on pgRouting gitter chat
- [x] put link of issue on pgRouting gitter chat

**Comment by cvvergara** [comment]
This pass
