### ISSUE TITLE
Build locally pgRouting

### ISSUE THREAD

**Issue by cOsprey** [cOsprey/GSoC-pgRouting#2]
- [x] Install requirements
- [x] create new branch with name `gsoc-test`
- [x] push the newly created branch
- [x] build locally pgRouting
- [x] put link of issue on pgRouting gitter chat

**Comment by cOsprey** [comment]
### Install requirements

For compiling pgRouting the following dependencies are required:
1.     C and C++ compilers
2.     Postgresql 
3.     The Boost Graph Library (BGL)
4.     CMake

**Comment by cOsprey** [comment]
### Build locally pgrouting:

- **mkdir build**
- **cd build**
- **cmake**
       -- Setting build type to 'Debug' as none was specified.
-- CMAKE_BUILD_TYPE Debug
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DOXYGEN_MINIMUM_VERSION=1.7
-- SPHINX_MINIMUM_VERSION=1.1
-- POSTGRESQL_MINIMUM_VERSION=9.2.0
-- POSTGIS_MINIMUM_VERSION=2.0.0
-- GNU_CXX_MINIMUM_VERSION=4.6
-- CLANG_CXX_MINIMUM_VERSION=
-- MSVC_CXX_MINIMUM_VERSION=18.0
-- dir='/home/osprey/pgrouting/cmake'
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Using  -std=c++11.
-- Found Perl: /usr/bin/perl (found version "5.26.1") 
-- POSTGRESQL_PG_CONFIG is /usr/bin/pg_config
-- POSTGRESQL_EXECUTABLE is /usr/lib/postgresql/11/bin/postgres
-- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 11.7 (Ubuntu 11.7-2.pgdg18.04+1)
-- POSTGRESQL_INCLUDE_DIR: /usr/include/postgresql/10/server
-- POSTGRESQL_LIBRARIES: /usr/lib/x86_64-linux-gnu
-- PGSQL_VERSION=117
-- Boost version: 1.65.1
-- Boost headers were found here: /usr/include
-- Boost VERSION 1.65.1
-- BOOST_VERSION_OK 1
-- BOOST_Geometry_VERSION_OK 1
-- Performing Test C_COMPILER_SUPPORTS_FPIC
-- Performing Test C_COMPILER_SUPPORTS_FPIC - Success
-- Performing Test CXX_COMPILER_SUPPORTS_FPIC
-- Performing Test CXX_COMPILER_SUPPORTS_FPIC - Success
-- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH
-- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH - Success
-- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH
-- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/osprey/pgrouting/build
- **make**
   Scanning dependencies of target breadthFirstSearch
[  0%] Building C object src/breadthFirstSearch/CMakeFiles/breadthFirstSearch.dir/breadthFirstSearch.c.o
[  1%] Building CXX object src/breadthFirstSearch/CMakeFiles/breadthFirstSearch.dir/breadthFirstSearch_driver.cpp.o
[  2%] Building C object src/breadthFirstSearch/CMakeFiles/breadthFirstSearch.dir/binaryBreadthFirstSearch.c.o
[  2%] Building CXX object src/breadthFirstSearch/CMakeFiles/breadthFirstSearch.dir/binaryBreadthFirstSearch_driver.cpp.o
[  2%] Built target breadthFirstSearch
Scanning dependencies of target common
[  3%] Building C object src/common/CMakeFiles/common.dir/postgres_connection.c.o
[  4%] Building C object src/common/CMakeFiles/common.dir/e_report.c.o
[  4%] Building CXX object src/common/CMakeFiles/common.dir/basePath_SSEC.cpp.o
[  5%] Building C object src/common/CMakeFiles/common.dir/points_input.c.o
[  5%] Building C object src/common/CMakeFiles/common.dir/matrixRows_input.c.o
[  6%] Building C object src/common/CMakeFiles/common.dir/get_check_data.c.o
[  6%] Building C object src/common/CMakeFiles/common.dir/edges_input.c.o
[  7%] Building C object src/common/CMakeFiles/common.dir/orders_input.c.o
[  8%] Building C object src/common/CMakeFiles/common.dir/vehicles_input.c.o
[  8%] Building C object src/common/CMakeFiles/common.dir/pgr_point_input.c.o
[  9%] Building C object src/common/CMakeFiles/common.dir/restrictions_input.c.o
[  9%] Building C object src/common/CMakeFiles/common.dir/coordinates_input.c.o
[ 10%] Building C object src/common/CMakeFiles/common.dir/arrays_input.c.o
[ 10%] Building C object src/common/CMakeFiles/common.dir/delauny_input.c.o
[ 11%] Building C object src/common/CMakeFiles/common.dir/check_parameters.c.o
[ 12%] Building C object src/common/CMakeFiles/common.dir/time_msg.c.o
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/pgr_assert.cpp.o
[ 13%] Building CXX object src/common/CMakeFiles/common.dir/identifier.cpp.o
[ 13%] Building CXX object src/common/CMakeFiles/common.dir/basic_vertex.cpp.o
[ 14%] Building CXX object src/common/CMakeFiles/common.dir/xy_vertex.cpp.o
[ 15%] Building CXX object src/common/CMakeFiles/common.dir/ch_vertex.cpp.o
[ 15%] Building CXX object src/common/CMakeFiles/common.dir/ch_edge.cpp.o
[ 16%] Building CXX object src/common/CMakeFiles/common.dir/basic_edge.cpp.o
[ 16%] Building CXX object src/common/CMakeFiles/common.dir/pgr_alloc.cpp.o
[ 16%] Built target common
Scanning dependencies of target dijkstra
[ 17%] Building C object src/dijkstra/CMakeFiles/dijkstra.dir/dijkstra.c.o
[ 18%] Building C object src/dijkstra/CMakeFiles/dijkstra.dir/dijkstraVia.c.o
[ 18%] Building CXX object src/dijkstra/CMakeFiles/dijkstra.dir/dijkstra_driver.cpp.o
[ 19%] Building CXX object src/dijkstra/CMakeFiles/dijkstra.dir/dijkstraVia_driver.cpp.o
[ 19%] Built target dijkstra
Scanning dependencies of target allpairs
[ 20%] Building C object src/allpairs/CMakeFiles/allpairs.dir/floydWarshall.c.o
[ 20%] Building CXX object src/allpairs/CMakeFiles/allpairs.dir/floydWarshall_driver.cpp.o
[ 21%] Building C object src/allpairs/CMakeFiles/allpairs.dir/johnson.c.o
[ 21%] Building CXX object src/allpairs/CMakeFiles/allpairs.dir/johnson_driver.cpp.o
[ 21%] Built target allpairs
Scanning dependencies of target astar
[ 22%] Building C object src/astar/CMakeFiles/astar.dir/astar.c.o
[ 22%] Building CXX object src/astar/CMakeFiles/astar.dir/astar_driver.cpp.o
[ 22%] Built target astar
Scanning dependencies of target driving_distance
[ 22%] Building C object src/driving_distance/CMakeFiles/driving_distance.dir/many_to_dist_driving_distance.c.o
[ 23%] Building C object src/driving_distance/CMakeFiles/driving_distance.dir/many_to_dist_withPointsDD.c.o
[ 23%] Building CXX object src/driving_distance/CMakeFiles/driving_distance.dir/drivedist_driver.cpp.o
[ 24%] Building CXX object src/driving_distance/CMakeFiles/driving_distance.dir/withPoints_dd_driver.cpp.o
[ 24%] Built target driving_distance
Scanning dependencies of target ksp
[ 25%] Building C object src/ksp/CMakeFiles/ksp.dir/ksp.c.o
[ 25%] Building CXX object src/ksp/CMakeFiles/ksp.dir/ksp_driver.cpp.o
[ 26%] Building C object src/ksp/CMakeFiles/ksp.dir/withPoints_ksp.c.o
[ 26%] Building CXX object src/ksp/CMakeFiles/ksp.dir/withPoints_ksp_driver.cpp.o
[ 27%] Building C object src/ksp/CMakeFiles/ksp.dir/turnRestrictedPath.c.o
[ 27%] Building CXX object src/ksp/CMakeFiles/ksp.dir/turnRestrictedPath_driver.cpp.o
[ 27%] Built target ksp
Scanning dependencies of target tsp
[ 27%] Building C object src/tsp/CMakeFiles/tsp.dir/euclideanTSP.c.o
[ 28%] Building C object src/tsp/CMakeFiles/tsp.dir/TSP.c.o
[ 29%] Building CXX object src/tsp/CMakeFiles/tsp.dir/TSP_driver.cpp.o
[ 29%] Building CXX object src/tsp/CMakeFiles/tsp.dir/euclideanTSP_driver.cpp.o
[ 30%] Building CXX object src/tsp/CMakeFiles/tsp.dir/euclideanDmatrix.cpp.o
[ 30%] Building CXX object src/tsp/CMakeFiles/tsp.dir/tour.cpp.o
[ 30%] Built target tsp
Scanning dependencies of target alpha_shape
[ 31%] Building CXX object src/alpha_shape/CMakeFiles/alpha_shape.dir/pgr_alphaShape.cpp.o
[ 32%] Building C object src/alpha_shape/CMakeFiles/alpha_shape.dir/alphaShape.c.o
[ 32%] Building CXX object src/alpha_shape/CMakeFiles/alpha_shape.dir/alphaShape_driver.cpp.o
[ 32%] Built target alpha_shape
Scanning dependencies of target bdAstar
[ 33%] Building C object src/bdAstar/CMakeFiles/bdAstar.dir/bdAstar.c.o
[ 33%] Building CXX object src/bdAstar/CMakeFiles/bdAstar.dir/bdAstar_driver.cpp.o
[ 33%] Built target bdAstar
Scanning dependencies of target bdDijkstra
[ 34%] Building C object src/bdDijkstra/CMakeFiles/bdDijkstra.dir/bdDijkstra.c.o
[ 35%] Building CXX object src/bdDijkstra/CMakeFiles/bdDijkstra.dir/bdDijkstra_driver.cpp.o
[ 35%] Built target bdDijkstra
Scanning dependencies of target trsp
[ 35%] Building C object src/trsp/CMakeFiles/trsp.dir/trsp.c.o
/home/osprey/pgrouting/src/trsp/trsp.c: In function ‘compute_trsp’:
/home/osprey/pgrouting/src/trsp/trsp.c:316:17: warning: conversion to ‘uint32_t {aka unsigned int}’ from ‘uint64 {aka long unsigned int}’ may alter its value [-Wconversion]
       ntuples = SPI_processed;
                 ^~~~~~~~~~~~~
/home/osprey/pgrouting/src/trsp/trsp.c:434:21: warning: conversion to ‘uint32_t {aka unsigned int}’ from ‘uint64 {aka long unsigned int}’ may alter its value [-Wconversion]
           ntuples = SPI_processed;
                     ^~~~~~~~~~~~~
[ 36%] Building CXX object src/trsp/CMakeFiles/trsp.dir/trsp_core.cpp.o
[ 37%] Building CXX object src/trsp/CMakeFiles/trsp.dir/GraphDefinition.cpp.o
[ 37%] Building C object src/trsp/CMakeFiles/trsp.dir/new_trsp.c.o
[ 38%] Building CXX object src/trsp/CMakeFiles/trsp.dir/edgeInfo.cpp.o
[ 38%] Building CXX object src/trsp/CMakeFiles/trsp.dir/pgr_trspHandler.cpp.o
[ 39%] Building CXX object src/trsp/CMakeFiles/trsp.dir/trsp_driver.cpp.o
[ 39%] Built target trsp
Scanning dependencies of target max_flow
[ 39%] Building C object src/max_flow/CMakeFiles/max_flow.dir/max_flow.c.o
[ 40%] Building C object src/max_flow/CMakeFiles/max_flow.dir/minCostMaxFlow.c.o
[ 41%] Building C object src/max_flow/CMakeFiles/max_flow.dir/maximum_cardinality_matching.c.o
[ 41%] Building C object src/max_flow/CMakeFiles/max_flow.dir/edge_disjoint_paths.c.o
[ 42%] Building CXX object src/max_flow/CMakeFiles/max_flow.dir/max_flow_driver.cpp.o
[ 42%] Building CXX object src/max_flow/CMakeFiles/max_flow.dir/maximum_cardinality_matching_driver.cpp.o
[ 43%] Building CXX object src/max_flow/CMakeFiles/max_flow.dir/edge_disjoint_paths_driver.cpp.o
[ 43%] Building CXX object src/max_flow/CMakeFiles/max_flow.dir/minCostMaxFlow_driver.cpp.o
[ 44%] Building CXX object src/max_flow/CMakeFiles/max_flow.dir/pgr_maxflow.cpp.o
[ 45%] Building CXX object src/max_flow/CMakeFiles/max_flow.dir/pgr_flowgraph.cpp.o
[ 45%] Building CXX object src/max_flow/CMakeFiles/max_flow.dir/pgr_minCostMaxFlow.cpp.o
[ 45%] Built target max_flow
Scanning dependencies of target contraction
[ 46%] Building C object src/contraction/CMakeFiles/contraction.dir/contractGraph.c.o
[ 46%] Building CXX object src/contraction/CMakeFiles/contraction.dir/contractGraph_driver.cpp.o
[ 47%] Building CXX object src/contraction/CMakeFiles/contraction.dir/pgr_contract.cpp.o
[ 47%] Built target contraction
Scanning dependencies of target pickDeliver
[ 47%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/base_node.cpp.o
[ 48%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/dnode.cpp.o
[ 49%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/node.cpp.o
[ 49%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/tw_node.cpp.o
[ 50%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/vehicle_node.cpp.o
[ 50%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/order.cpp.o
[ 51%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pd_orders.cpp.o
[ 52%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/fleet.cpp.o
[ 52%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/vehicle.cpp.o
[ 53%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pd_problem.cpp.o
[ 53%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/vehicle_pickDeliver.cpp.o
[ 54%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/book_keeping.cpp.o
[ 54%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/solution.cpp.o
[ 55%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/initial_solution.cpp.o
[ 56%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/optimize.cpp.o
[ 56%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pgr_messages.cpp.o
[ 57%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pgr_pickDeliver.cpp.o
[ 57%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pickDeliverEuclidean_driver.cpp.o
[ 58%] Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pickDeliver_driver.cpp.o
[ 58%] Building C object src/pickDeliver/CMakeFiles/pickDeliver.dir/pickDeliverEuclidean.c.o
[ 59%] Building C object src/pickDeliver/CMakeFiles/pickDeliver.dir/pickDeliver.c.o
[ 59%] Built target pickDeliver
Scanning dependencies of target withPoints
[ 60%] Building C object src/withPoints/CMakeFiles/withPoints.dir/withPoints.c.o
[ 60%] Building CXX object src/withPoints/CMakeFiles/withPoints.dir/get_new_queries.cpp.o
[ 61%] Building CXX object src/withPoints/CMakeFiles/withPoints.dir/withPoints_driver.cpp.o
[ 62%] Building CXX object src/withPoints/CMakeFiles/withPoints.dir/pgr_withPoints.cpp.o
[ 62%] Built target withPoints
Scanning dependencies of target lineGraph
[ 63%] Building C object src/lineGraph/CMakeFiles/lineGraph.dir/lineGraphFull.c.o
[ 64%] Building CXX object src/lineGraph/CMakeFiles/lineGraph.dir/lineGraphFull_driver.cpp.o
[ 64%] Building C object src/lineGraph/CMakeFiles/lineGraph.dir/lineGraph.c.o
[ 65%] Building CXX object src/lineGraph/CMakeFiles/lineGraph.dir/lineGraph_driver.cpp.o
[ 65%] Built target lineGraph
Scanning dependencies of target components
[ 66%] Building C object src/components/CMakeFiles/components.dir/connectedComponents.c.o
[ 66%] Building C object src/components/CMakeFiles/components.dir/strongComponents.c.o
[ 67%] Building C object src/components/CMakeFiles/components.dir/biconnectedComponents.c.o
[ 68%] Building C object src/components/CMakeFiles/components.dir/articulationPoints.c.o
[ 68%] Building C object src/components/CMakeFiles/components.dir/bridges.c.o
[ 69%] Building CXX object src/components/CMakeFiles/components.dir/componentsResult.cpp.o
[ 69%] Building CXX object src/components/CMakeFiles/components.dir/pgr_components.cpp.o
[ 70%] Building CXX object src/components/CMakeFiles/components.dir/connectedComponents_driver.cpp.o
[ 70%] Building CXX object src/components/CMakeFiles/components.dir/strongComponents_driver.cpp.o
[ 71%] Building CXX object src/components/CMakeFiles/components.dir/biconnectedComponents_driver.cpp.o
[ 72%] Building CXX object src/components/CMakeFiles/components.dir/articulationPoints_driver.cpp.o
[ 72%] Building CXX object src/components/CMakeFiles/components.dir/bridges_driver.cpp.o
[ 72%] Built target components
Scanning dependencies of target bellman_ford
[ 72%] Building C object src/bellman_ford/CMakeFiles/bellman_ford.dir/bellman_ford.c.o
[ 73%] Building CXX object src/bellman_ford/CMakeFiles/bellman_ford.dir/bellman_ford_driver.cpp.o
[ 73%] Building C object src/bellman_ford/CMakeFiles/bellman_ford.dir/edwardMoore.c.o
[ 74%] Building CXX object src/bellman_ford/CMakeFiles/bellman_ford.dir/edwardMoore_driver.cpp.o
[ 74%] Built target bellman_ford
Scanning dependencies of target cpp_common
[ 74%] Building CXX object src/cpp_common/CMakeFiles/cpp_common.dir/Dmatrix.cpp.o
[ 75%] Building CXX object src/cpp_common/CMakeFiles/cpp_common.dir/compPaths.cpp.o
[ 76%] Building CXX object src/cpp_common/CMakeFiles/cpp_common.dir/rule.cpp.o
[ 76%] Building CXX object src/cpp_common/CMakeFiles/cpp_common.dir/bpoint.cpp.o
[ 76%] Built target cpp_common
Scanning dependencies of target dagShortestPath
[ 77%] Building C object src/dagShortestPath/CMakeFiles/dagShortestPath.dir/dagShortestPath.c.o
[ 77%] Building CXX object src/dagShortestPath/CMakeFiles/dagShortestPath.dir/dagShortestPath_driver.cpp.o
[ 77%] Built target dagShortestPath
Scanning dependencies of target chinese
[ 78%] Building C object src/chinese/CMakeFiles/chinese.dir/chinesePostman.c.o
[ 78%] Building CXX object src/chinese/CMakeFiles/chinese.dir/chinesePostman_driver.cpp.o
[ 78%] Built target chinese
Scanning dependencies of target spanningTree
[ 79%] Building CXX object src/spanningTree/CMakeFiles/spanningTree.dir/mst_common.cpp.o
[ 79%] Building CXX object src/spanningTree/CMakeFiles/spanningTree.dir/details.cpp.o
[ 80%] Building C object src/spanningTree/CMakeFiles/spanningTree.dir/kruskal.c.o
[ 80%] Building CXX object src/spanningTree/CMakeFiles/spanningTree.dir/kruskal_driver.cpp.o
[ 81%] Building C object src/spanningTree/CMakeFiles/spanningTree.dir/prim.c.o
[ 81%] Building CXX object src/spanningTree/CMakeFiles/spanningTree.dir/prim_driver.cpp.o
[ 81%] Built target spanningTree
Scanning dependencies of target mincut
[ 82%] Building C object src/mincut/CMakeFiles/mincut.dir/stoerWagner.c.o
[ 82%] Building CXX object src/mincut/CMakeFiles/mincut.dir/stoerWagner_driver.cpp.o
[ 82%] Built target mincut
Scanning dependencies of target version
[ 83%] Building C object src/version/CMakeFiles/version.dir/version.c.o
[ 83%] Building C object src/version/CMakeFiles/version.dir/_version.c.o
[ 83%] Built target version
Scanning dependencies of target topologicalSort
[ 84%] Building C object src/topologicalSort/CMakeFiles/topologicalSort.dir/topologicalSort.c.o
[ 85%] Building CXX object src/topologicalSort/CMakeFiles/topologicalSort.dir/topologicalSort_driver.cpp.o
[ 85%] Built target topologicalSort
Scanning dependencies of target transitiveClosure
[ 85%] Building C object src/transitiveClosure/CMakeFiles/transitiveClosure.dir/transitiveClosure.c.o
[ 86%] Building CXX object src/transitiveClosure/CMakeFiles/transitiveClosure.dir/transitiveClosure_driver.cpp.o
[ 86%] Built target transitiveClosure
Scanning dependencies of target pgrouting-3.0
[ 87%] Linking CXX shared library lib/libpgrouting-3.0.so
[ 87%] Built target pgrouting-3.0
Scanning dependencies of target PGROUTING_SQL_FILE
[ 87%] Generating pgrouting--3.0.0.sql
[ 87%] Built target PGROUTING_SQL_FILE
Scanning dependencies of target update_files
[ 88%] Generating pgrouting--2.6.3--3.0.0.sql
[ 88%] Generating pgrouting--2.6.2--3.0.0.sql
[ 89%] Generating pgrouting--2.6.1--3.0.0.sql
[ 90%] Generating pgrouting--2.6.0--3.0.0.sql
[ 90%] Generating pgrouting--2.5.5--3.0.0.sql
[ 91%] Generating pgrouting--2.5.4--3.0.0.sql
[ 91%] Generating pgrouting--2.5.3--3.0.0.sql
[ 92%] Generating pgrouting--2.5.2--3.0.0.sql
[ 93%] Generating pgrouting--2.5.1--3.0.0.sql
[ 93%] Generating pgrouting--2.5.0--3.0.0.sql
[ 94%] Generating pgrouting--2.4.2--3.0.0.sql
[ 94%] Generating pgrouting--2.4.1--3.0.0.sql
[ 95%] Generating pgrouting--2.4.0--3.0.0.sql
[ 95%] Generating pgrouting--2.3.2--3.0.0.sql
[ 96%] Generating pgrouting--2.3.1--3.0.0.sql
[ 97%] Generating pgrouting--2.3.0--3.0.0.sql
[ 97%] Generating pgrouting--2.2.4--3.0.0.sql
[ 98%] Generating pgrouting--2.2.3--3.0.0.sql
[ 98%] Generating pgrouting--2.2.2--3.0.0.sql
[ 99%] Generating pgrouting--2.2.1--3.0.0.sql
[ 99%] Generating pgrouting--2.2.0--3.0.0.sql
[100%] Built target update_files

- **sudo make install**

  [sudo] password for osprey: 
[  2%] Built target breadthFirstSearch
[ 16%] Built target common
[ 19%] Built target dijkstra
[ 21%] Built target allpairs
[ 22%] Built target astar
[ 24%] Built target driving_distance
[ 27%] Built target ksp
[ 30%] Built target tsp
[ 32%] Built target alpha_shape
[ 33%] Built target bdAstar
[ 35%] Built target bdDijkstra
[ 39%] Built target trsp
[ 45%] Built target max_flow
[ 47%] Built target contraction
[ 59%] Built target pickDeliver
[ 62%] Built target withPoints
[ 65%] Built target lineGraph
[ 72%] Built target components
[ 74%] Built target bellman_ford
[ 76%] Built target cpp_common
[ 77%] Built target dagShortestPath
[ 78%] Built target chinese
[ 81%] Built target spanningTree
[ 82%] Built target mincut
[ 83%] Built target version
[ 85%] Built target topologicalSort
[ 86%] Built target transitiveClosure
[ 87%] Built target pgrouting-3.0
[ 87%] Built target PGROUTING_SQL_FILE
[100%] Built target update_files
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/lib/postgresql/11/lib/libpgrouting-3.0.so
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.6.3--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.6.2--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.6.1--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.6.0--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.5.5--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.5.4--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.5.3--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.5.2--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.5.1--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.5.0--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.4.2--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.4.1--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.4.0--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.3.2--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.3.1--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.3.0--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.2.4--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.2.3--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.2.2--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.2.1--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--2.2.0--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting--3.0.0.sql
-- Installing: /usr/share/postgresql/11/extension/pgrouting.control

**Comment by cvvergara** [comment]
This is a pass
