### ISSUE TITLE
Get familiar with C++

### ISSUE THREAD

**Issue by cOsprey** [cOsprey/GSoC-pgRouting#3]
- [x] https://www.youtube.com/watch?v=eidEEmGLQcU
  - [x] Make Report
- [x] https://www.youtube.com/watch?v=u5senBJUkPc
  - [x] Make Report
- [ ] https://www.youtube.com/watch?v=YnWhqhNdYyk
  - [ ] Make Report
- [ ] https://www.youtube.com/watch?v=1OEu9C51K2A
  - [ ] Make Report
- [ ] https://www.youtube.com/watch?v=xnqTKD8uD64
  - [ ] Make Report
- [ ] https://www.youtube.com/watch?v=86xWVb4XIyE
  - [ ] Make Report
```

**Comment by cOsprey** [comment]
Video 1: STL Algorithms
![1](https://user-images.githubusercontent.com/56584099/77951356-902b7380-72e7-11ea-95d3-561fd4fbf0cd.jpg)

**Comment by cOsprey** [comment]
Report 2

**Comment by cOsprey** [comment]
Report 3

**Comment by cOsprey** [comment]
### Report 4
![4](https://user-images.githubusercontent.com/56584099/77996594-863b5c00-734b-11ea-9f4e-34515eb35c58.jpg)

**Comment by cOsprey** [comment]
### Report 5
![5](https://user-images.githubusercontent.com/56584099/77997338-d666ee00-734c-11ea-93e8-53632918493b.jpg)

**Comment by cOsprey** [comment]
### Report 6: Bjarne Stroustrup - The Essence of C++
![6](https://user-images.githubusercontent.com/56584099/78000274-aa01a080-7351-11ea-9ba3-8f1e2b673045.jpg)

**Comment by cvvergara** [comment]
This test pass
